### ISSUE TITLE
Frontend - data-workflow - page profil

### ISSUE THREAD

**Issue by c-costin** [costin-projects/project-c-studio#172]
### Calls API

- [x] Orders
- [x] Favorites

### Actions

- [ ] Edit
- [ ] Delete Account
- [ ] Delete Favorite

### Think ! :warning: 

- [ ] Check if it is possible to redirect directly to the profile, order or favorite

**Comment by charlotte-carpentier** [comment]
@c-costin si tu peux jeter un œil à mon ddernier push, je patauge avec une erreur d'URL depuis un moment, concernant le import OrderController dans Order.svelte, j'ai utilisé des chemins relatifs, vérifié la casse, testé avec des chemins absolus, mis à jour mes dépendances mais ma page reste désespérément blanche et en erreur 500 =( =( =( 
Mais peut-être que je fais fausse route et que je me suis emmêlé les pinceaux avec ma "logique"...
